### PR TITLE
Fix to save entered addtional_classes class order.

### PR DESCRIPTION
**Pull request by FilippoIOVINE**

### CODE REVIEW

**Comment by FinalAngel** [comment]
@divio/django-cms-core would appreciate a review :)

**Comment by FilippoIOVINE** [comment]
Hi Angelo,
I have no idea what to do now.

**Comment by FinalAngel** [comment]
@FilippoIOVINE no worries :) I'm waiting now for a review and afterwards I merge this. A release might follow later this week or next.

**Comment by FilippoIOVINE** [comment]
Thanks Angelo

**Pull request merged**
